#!/usr/bin/env bash
set -eu
set -o pipefail
set -x
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
TEMP_DIR=$(mktemp -d -t gffXXXXXX)
STATE_DIR="$(readlink -f "$1")"

[[ ! -z "${TEMP_DIR}" ]] || exit 1
trap 'rm -rf -- "${TEMP_DIR}"' exit
if [[ -f "${STATE_DIR}/summary-version.txt" ]]; then
    VER=$(cat "${STATE_DIR}/summary-version.txt")
    VER=$((VER + 1))
    echo "${VER}" >"${TEMP_DIR}/summary-version.txt"
else
    echo "1" >"${TEMP_DIR}/summary-version.txt"
fi
cp "${SCRIPT_DIR}/../brochure"/*.typ "${TEMP_DIR}"
cp "${SCRIPT_DIR}/../brochure"/*.jpg "${TEMP_DIR}"
cp "${STATE_DIR}/summary.json" "${TEMP_DIR}"
cp "${STATE_DIR}/filter-summary.json" "${TEMP_DIR}"

typst compile "${TEMP_DIR}/filter-summary.typ"
cp "${TEMP_DIR}/filter-summary.pdf" "${STATE_DIR}"
cp "${TEMP_DIR}/summary-version.txt" "${STATE_DIR}"
